name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: prefix-dev/setup-pixi@v0.9.0
        with:
          pixi-version: v0.46.0

      - name: Run mypy checks
        run: pixi run mypy

      - name: Run ruff checks
        run: pixi run ruff

  test:
    name: Test Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [py310, py311, py312, py313]

    steps:
      - name: Clone repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: prefix-dev/setup-pixi@v0.9.0
        with:
          pixi-version: v0.46.0
          cache: false

      - name: Run tests with Python ${{ matrix.python-version }}
        run: pixi run -e ${{ matrix.python-version }} test
