name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  tasks:
    name: Run tasks
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: prefix-dev/setup-pixi@v0.8.3
        with:
          pixi-version: v0.46.0
          cache: true

      - name: Run mypy checks
        run: pixi run mypy

      - name: Run ruff checks
        run: pixi run ruff

      - name: Run tests
        run: pixi run test
