name: Publish to PyPi

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/pipelining-colemann

    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Hatch
        uses: pypa/hatch@install

      - name: Build package
        run: hatch build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
